### ISSUE TITLE
Autofocus iframe

### ISSUE THREAD

**Issue by lucat1** [csunibo/dynamik#12]
Ci lavorerei io ma non ho troppo tempo in questi giorni. Il problema che riscontro è che quando apro un file pdf non ho il focus sull'iframe che lo visualizza (i.e., non riesco a usare le frecce per muovermi nel pdf). Visto che l'intento è quello di imitare un browser nativo usando l'iframe, penso sia opportuno aggiungerlo. Penso basti metterlo nel on mount (o comunque, l'analogo in svelte) del componente che mostra l'iframe, cosi' viene applicato sia se carico la pagina da 0 sia se ci navigo dalla listing.

**Comment by VaiTon** [comment]
Dovrebbe essere fixata con [70ff02b](https://github.com/csunibo/dynamik/commit/70ff02b9483bd439a23a85c9452958588bab112e). Controlla se worka @lucat1

**Comment by samuelemusiani** [comment]
Dire che si è risolto, a me va tutto
