### ISSUE TITLE
Titolo da croppare 

### ISSUE THREAD

**Issue by Diebbo** [csunibo/dynamik#126]
Da telefono, il titolo della sezione "Ingegneria e scienze informatiche", storpia la pagina
 [![Screenshot_2023-10-23-11-26-07-78_e4424258c8b8649f6e67d283a50a2cbc.jpg](https://github.com/csunibo/dynamik/assets/95416239/3562d4c1-4a5a-4ce5-bfb9-990f003b0223)

**Comment by foxyseta** [comment]
@csunibo/frontend

**Comment by ali-benny** [comment]
# nuova proposta mobile per i breadcrumbs

**predefinito mobile:**
![image](https://github.com/csunibo/dynamik/assets/74602443/7a56f4dc-612c-4053-b789-f7bbd18a5d8d)

**opzione con git fuori dai breadcrumbs**
![image](https://github.com/csunibo/dynamik/assets/74602443/9e175263-65c8-4332-af6b-aab59d4c1795)


**quando clicco:**
![image](https://github.com/csunibo/dynamik/assets/74602443/428b3b7a-50ef-40c6-89d0-3ea01ff63d9f)

# nuova visualizzazione desktop [provvisoria]
ho spostato il logo git per averlo sempre accessibile @foxyseta @csunibo/frontend se non serve, lo rimetto dentro al breadcrumb

![image](https://github.com/csunibo/dynamik/assets/74602443/322d1229-1458-41be-88c5-e1e69fea1433)

**Comment by Diebbo** [comment]
Fighissimo
