### ISSUE TITLE
Briciola di pane mancante per CdL

### ISSUE THREAD

**Issue by foxyseta** [csunibo/dynamik#128]
Le briciole di pane al momento sono nel formato "Pagina iniziale > Insegnamento > Cartelle...", quindi manca un modo di tornare al CdL. Andrebbe sicuramente aggiunto (una volta c'era la freccia sulla destra che giustamente è stata rimossa).

**Comment by foxyseta** [comment]
Mi sembra sensato. D'altronde stiamo già facendo lo stesso per la home. Potremmo usare la stessa emoji del corso di laurea in questione, oppure andare a caccia di una generica icona "corso di laurea" (ma mi sembra difficile trovarla). Se però usiamo le emoji, tanto vale metterne una di più sensata per Cesena.

**Comment by ali-benny** [comment]
una cosa del genere? così è generico.. magari possiamo personalizzarlo con colori uno per CdL?
<img width="755" alt="image" src="https://github.com/csunibo/dynamik/assets/74602443/cc1d29e0-e3b0-48e6-b7d3-630336918caa">

o uno zaino magari colorato diverso per ogni CdL 
<img width="462" alt="image" src="https://github.com/csunibo/dynamik/assets/74602443/e72b2288-fda3-406d-bf5b-0b2534d28cdc">

o una cosa del genere
<img width="324" alt="image" src="https://github.com/csunibo/dynamik/assets/74602443/25f0b11a-8247-4d98-9298-2013b775f6a3">

**Comment by foxyseta** [comment]
Forse il cappello? Mi fa più a "Corso di laurea". Codificare tramite colori ci sta se sostituiamo le emoji, Sembra più una cosa estetica che altro però, quindi lo lascerei per il futuro.

**Comment by ali-benny** [comment]
> Forse il cappello? Mi fa più a "Corso di laurea". 

Ci sta ahahha

> Codificare tramite colori ci sta se sostituiamo le emoji, 

Io le toglierei proprio, non vorrei dire ma mettere 🥸 a cesena mi sembra un po' offensivo 

> Sembra più una cosa estetica che altro però, quindi lo lascerei per il futuro.

Ah okay, per me non cambia farla anche adesso sinceramente, dite voi @csunibo/frontend

**Comment by foxyseta** [comment]
> Io le toglierei proprio, non vorrei dire ma mettere 🥸 a cesena mi sembra un po' offensivo

Giuro lo ha scelto il loro rappresentante ahahahahah

> Ah okay, per me non cambia farla anche adesso sinceramente, dite voi @csunibo/frontend

se per te non è una scocciatura anche per me va bene farla ora. Giocosamente dico spesso che le emoji fanno molto soy-dev apple, ma la verità è che non sono neanche superaccessibili (a meno di non usare tag aria molto specifiche, il lettore legge il nome dell'emoji senza distinguerlo dal testo).

**Comment by ali-benny** [comment]
> > Io le toglierei proprio, non vorrei dire ma mettere 🥸 a cesena mi sembra un po' offensivo
> 
> Giuro lo ha scelto il loro rappresentante ahahahahah

AHAHHA OKAY

> > Ah okay, per me non cambia farla anche adesso sinceramente, dite voi @csunibo/frontend
> 
> se per te non è una scocciatura anche per me va bene farla ora. Giocosamente dico spesso che le emoji fanno molto soy-dev apple, ma la verità è che non sono neanche superaccessibili (a meno di non usare tag aria molto specifiche, il lettore legge il nome dell'emoji senza distinguerlo dal testo).

A questo punto proporrei di colorare i bottoni nella homepage dedicati ai CdL con un loro colore identificativo, che useremo poi nelle breadcrumbs. 
Sarebbe carino poi riusare questo colore anche nella nav bar per identificare a colpo d'occhio in quale insegnamento si è.

**Comment by VaiTon** [comment]
Il problema è che non sappiamo da dove l'utente è arrivato. Il namespace dei nomi delle materie è piatto.

Una soluzione sarebbe mantenere nello stato dell'app svelte (via stores) se l'utente è entrato nella materia da uno specifico corso di studi ed _eventualmente_ mostrarlo nel componente breadcrumbs

**Comment by VaiTon** [comment]
> Io le toglierei proprio, non vorrei dire ma mettere 🥸 a cesena mi sembra un po' offensivo

![immagine](https://github.com/csunibo/dynamik/assets/12072630/8e36d3da-5434-413b-9222-ff012b282e85)
Actually...

**Comment by ali-benny** [comment]
> Il problema è che non sappiamo da dove l'utente è arrivato. Il namespace dei nomi delle materie è piatto.
> 
> Una soluzione sarebbe mantenere nello stato dell'app svelte (via stores) se l'utente è entrato nella materia da uno specifico corso di studi ed _eventualmente_ mostrarlo nel componente breadcrumbs

Dici perchè alcuni CdL hanno insegnamenti "doppioni" in lista che rimandano ad altri CdL [per i facoltativi]?

**Comment by foxyseta** [comment]
Potenzialmente sì. Possiamo anche lasciar perdere a questo punto.

**Comment by ali-benny** [comment]
> Potenzialmente sì. 

Attualmente mi sembra che non sia così però


> Possiamo anche lasciar perdere a questo punto.

Oks, appena rientro vedo di iniziarci a lavorare

**Comment by foxyseta** [comment]
Eh diciamo che la politica teorica da adottare era di fare così a breve.

@VaiTon se linkassimo al primo CdL che elenca tale corso tale che `optional: false`?

**Comment by VaiTon** [comment]
> Eh diciamo che la politica teorica da adottare era di fare così a breve.
> 
> @VaiTon se linkassimo al primo CdL che elenca tale corso tale che `optional: false`?

Andrebbe bene nel caso accedessi direttamente dal link della materia. Se accedo da una dashboard di un altro corso risulta poco intuitivo secondo me trovarsi il nome di un altro corso. Io farei con uno store [^1] a questo punto del tipo `lastVisitedCourse` e da quello creerei (se != null) la parte del breadcrumb che ci interessa.

[^1]: https://kit.svelte.dev/docs/state-management#using-stores-with-context

**Comment by foxyseta** [comment]
Massì. Per la gente sembrerà magia nera forse non avere una struttura delle pagine ad albero forse ma questo sarebbe l'ideale.
