### ISSUE TITLE
Visualizzatore quaderni Jupiter

### ISSUE THREAD

**Issue by foxyseta** [csunibo/dynamik#132]
Diversi insegnamenti fanno uso di quaderni Jupiter. Vogliamo aggiungere un visualizzatore o qualcosa di simile (senza lasciare eseguire codice ovviamente)?

**Comment by ali-benny** [comment]
Mi sembra una bellissima idea

**Comment by ali-benny** [comment]
Ho guardato un po' e ci sono delle librerie che fanno il viewer (come `nbviewer`) ma è un casino e sinceramente non sono riuscita

**Comment by foxyseta** [comment]
Io sicuramente in queste settimane non riesco a guardarci. Etichetto come "help wanted" e la lascerei aperta.

**Comment by samuelemusiani** [comment]
Ma se invece convertissimo i notebook lato statik in html e servissimo semplicemente quelli? Alla fine come facciamo con latex, typst e tutti i doc

**Comment by ali-benny** [comment]
> Ma se invece convertissimo i notebook lato statik in html e servissimo semplicemente quelli? Alla fine come facciamo con latex, typst e tutti i doc

Se ti va e hai tempo per me è super oks

**Comment by samuelemusiani** [comment]
Closed by https://github.com/csunibo/build-image/pull/11 and https://github.com/csunibo/config/pull/63
