### ISSUE TITLE
500 sulle pagine dei CdL per CSR

### ISSUE THREAD

**Issue by foxyseta** [csunibo/dynamik#146]
Sull'istanza ospitata da GitHub Pages le pagine dei CdL restituiscono 500:
https://csunibo.github.io/dynamik/dash/informatica

**Comment by ali-benny** [comment]
in teoria questa istanza non dovrebbe essere usata così da quanto avevamo detto, ho capito male?

**Comment by foxyseta** [comment]
No abbiamo ripetuto in chat qualche giorno fa che è una delle nostre tre istanze legittime (anche se insieme a vercel è una di riserva). Se era uno di quei messaggi che ti ho riassunto come "nulla di importante" allora mi sono sbagliato ahahahaha

**Comment by foxyseta** [comment]
A prescindere dalla particolare istanza GitHub, questo è un problema che si estende ovunque nello scenario SSR, e stiamo proponendo dynamik come applicativo funzionante anche per SSR.

**Comment by VaiTon** [comment]
Giusto per chiarire: il deploy di GitHub non usa SSR. E' tutto runnato dal browser, quindi qui è un problema della mancanza di SSR.

**Comment by foxyseta** [comment]
Sì avrei dovuto scrivere non-SSR o è tremendamente fuorviamente

**Comment by foxyseta** [comment]
Rinominato tutto per usare CSR uniformemente

**Comment by ali-benny** [comment]
ma quindi in base all'url dovremmo gestire con una cosa del genere https://kit.svelte.dev/docs/page-options#csr ?

**Comment by VaiTon** [comment]
Nono, quelle opzioni non bisogna toccarle
