### ISSUE TITLE
500 internal server error on directories

### ISSUE THREAD

**Issue by musianisamuele** [csunibo/dynamik#151]
Se navigate nel sito, dopo un po' riscontrare un `500 internal server error`. Questo succede solo nelle directories. Se si torna indietro e si rientra nella cartella riprende a funzionare

**Comment by ali-benny** [comment]
penso sia perchè si perde il ?from=... @VaiTon

**Comment by musianisamuele** [comment]
Purtroppo non si è risolto

**Comment by ali-benny** [comment]
Closed by #156

**Comment by musianisamuele** [comment]
Sembra che adesso si sia effettivamente risolto, brava!
