### ISSUE TITLE
The download button does not work for some files

### ISSUE THREAD

**Issue by samuelemusiani** [csunibo/dynamik#189]
Ho notato che su alcuni file il pulsante di download non funziona. Quello che scarica è un file da circa 6.6Kb che però risulta illeggibile e il browser non riesce neanche ad aprirlo. È importante notare che se non si passa dal pulsante download, ma si clicca direttamente sul nome del file da scaricare il file viene aperto correttamente.

Questo non capita su tutti i file ma solo su alcuni, lascio di seguito alcuni link su cui provare:
https://risorse.students.cs.unibo.it/analisi-matematica/appunti?from=informatica
https://risorse.students.cs.unibo.it/analisi-matematica/prove?from=informatica
https://risorse.students.cs.unibo.it/logica-per-informatica/prove?from=informatica

Mentre per esempio qui funziona:
https://risorse.students.cs.unibo.it/algebra-e-geometria/prove?from=informatica

**Comment by musianisamuele** [comment]
Ho notato che da telefono, per i download non funzionanti, mi scarica un file html con scritto che la risorsa da me cercata non può essere trovata. Es: "https://csunibo.github.io/analisi-matematica/appunti/modulo1-musiani-samuele.pdf could not be found"

Da computer il file che scarica, nonostante abbia `.pdf` come estensione ha del contenuto `html`. Vi lascio in allegato un di questi file in modo che possiate indagare il contenuto.
[modulo1-musiani-samuele.pdf](https://github.com/csunibo/dynamik/files/13627548/modulo1-musiani-samuele.pdf)

**Comment by ali-benny** [comment]
ho scaricato un file corrotto da `/logica-per-informatica` e mettendolo con l'estensione `.html` il browser renderizza questo
![image](https://github.com/csunibo/dynamik/assets/74602443/655c958b-2d4a-4cb4-9815-ebd7eb6b163b)
con tutto il file navigabile, giusto un po' piccolino

**Comment by musianisamuele** [comment]
Mi sembra che il problema persista

**Comment by VaiTon** [comment]
Mi sa che è cambiato qualcosa in statik, perchè adesso richiediamo i file a `https://risorse.students.cs.unibo.it/analisi-matematica/appunti/appunti-prof-morbidelli`

**Comment by VaiTon** [comment]
In localhost (causa cors non mi va più)

**Comment by VaiTon** [comment]
Comunque tutto il meccanismo della fetch e del Blob è orribile. Io proporrei di toglierlo e basta.

**Comment by samuelemusiani** [comment]
> Comunque tutto il meccanismo della fetch e del Blob è orribile. Io proporrei di toglierlo e basta.

A cosa servirebbe questo meccanismo? (scusa ma non ho idea di come funzioni dynamik in questo momento)

**Comment by VaiTon** [comment]
Visto che utilizziamo github pages come hosting dei file, non abbiamo controllo sugli header che vengono inviati in seguito ad una risposta. 

Per scaricare un file (ovvero forzare il browser a scaricare un file invece di visualizzarlo) è necessario impostare degli header particolari (https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition). 

Al momento per bypassare questo usiamo un trucchetto in dynamic che consiste nello scaricare il file via `fetch` e poi creare un `<a>` finto con il contenuto del file, in modo tale che al click venga scaricato il file direttamente dalla pagina web. Ovviamente questo è sia poco accessibile che error-prone, quindi direi di toglierlo definitivamente e stop.

**Comment by samuelemusiani** [comment]
Ok grazie mille. Per me va bene cambiare, soprattutto perché non sembra un gran che il bypass che usiamo ahah. Immagino che però questo implichi usare gli header che mi hai linkato giusto?

**Comment by lucat1** [comment]
Possiamo lasciarlo e mettere un proxy in adm che aggiunge gli header come alternativa

**Comment by VaiTon** [comment]
@lucat1 ci avevo pensato, ma il problema è che poi le richieste a github sarebbero tutte da parte nostra, quindi dovremmo implementare rate-limiting forte.

**Comment by samuelemusiani** [comment]
Closed by #288
