### ISSUE TITLE
bug: dash/undefined

### ISSUE THREAD

**Issue by ali-benny** [csunibo/dynamik#194]
Alla prima apertura di un'istanza dopo il nuovo aggiornamento di un degree preferito [#163 #167 ] tenta il redirect su `/dash/undefined` dando errore 404.
Provando a tornare indietro con il bottone a disposizione della pagina rimanda sempre lì e non porta mai l'utente sulla "homepage"

**Comment by samuelemusiani** [comment]
Un mio amico ha appena riscontrare il problema. Aveva già utilizzato risorse e dopo l'aggiornamento dava il problema descritto dall'Alice. Il fatto è che se si va in incognito la pagina funziona bene, quindi sembra un problema di quello che veniva salvato prima.

Salvavamo qualcosa in locale prima di #163 #167?

**Comment by ali-benny** [comment]
> Salvavamo qualcosa in locale prima di #163 #167?

yesss

**Comment by samuelemusiani** [comment]
> > Salvavamo qualcosa in locale prima di #163 #167?
> 
> yesss
Potrebbe tranquillamente essere quello allora il problema

**Comment by ali-benny** [comment]
Non riesco a capire come riprodurre il problema per capire se è fixato o meno

**Comment by ali-benny** [comment]
Buildando in locale con `pnpm build` e mandando la `npm run preview` si ottiene il nostro "bellissimo" _404 error dash/undefined_

**Comment by Flecart** [comment]
> Buildando in locale con `pnpm build` e mandando la `npm run preview` si ottiene il nostro "bellissimo" _404 error dash/undefined_

Ho fatto questo e non ho errore, mmm. La cosa strana è che ho messo un default esplicito e non capisco bene come può succedere che sia undefined.
