### ISSUE TITLE
feat: done flag

### ISSUE THREAD

**Issue by ali-benny** [csunibo/dynamik#195]
Preparando gli esami ho pensato che sarebbe carino se si potesse aggiungere un'impostazione per poter spuntare quali file si sono letti/fatti, un po' come una todo list: magari cliccando sull'icona del file viene una spunta e cambia colore il link o viene barrato

**Comment by ali-benny** [comment]
anteprima v1.0
![image](https://github.com/csunibo/dynamik/assets/74602443/f75a30db-92f6-4410-824e-0e7e5eaff191)

**Comment by samuelemusiani** [comment]
Per me ci sta, aspettiamo la pr
