### ISSUE TITLE
Fuzzy finder

### ISSUE THREAD

**Issue by foxyseta** [csunibo/dynamik#3]
> Al momento il sito statico generato non fornisce nessun meccanismo per la ricerca dei conenuti. Le cartelle cercano di essere strutturate in modo omogeneo fra i vari insegnamenti, senza complicazioni, ma non sempre questo basta per trovare quello che si vuole velocemente.

Trasferita da csunibo/template. Questa feature sarà implementata in dynamik.

**Comment by VaiTon** [comment]
@lucat1 nel vecchio dynamik come era implementata? Query a fuzzy.json e da li ricavo i dati tranquillamente?

**Comment by lucat1** [comment]
Yes, posso farlo io se vuoi. La "logica" si puo' copa-incollare, usavo una qualche libreria.

Per i key bind ho visto che svelte ha un esempio carino sulla loro docu che si potrebbe copiare, ma bisogna schiaffare un pulsante (che avrei messo in ogni caso) nelle pagine di listing. Pero' poi si limita l'utilizzo del finder a queste pagine. Se c'e' un modo (con qualche libreria esterna a svelte immagino) di farlo "globalmente" e' piu carino.

**Comment by VaiTon** [comment]
Al momento il fuzzy finder è implementato per materia (aperta una materia, `Ctrl+k`). Manca aggiungere il btn per farlo aprire da GUI.

**Comment by lucat1** [comment]
Daje ottimo! avendo un bel serverino a disposizione (che tanto tocca mettere per la cosa dell'upload) possiamo anche mettere la ricerca csunibo-wide. Ancora meglio qualcosa tipo mellisearch o the like per indicizzare tutti i documenti. È una possibilità interessante secondo me, ma priorità bassa rispetto al resto.

**Comment by kocierik** [comment]
#59 closed
