### ISSUE TITLE
Estrarre elenco dei corsi in un JSON

### ISSUE THREAD

**Issue by foxyseta** [csunibo/dynamik#37]
In `teachings.ts` sono hardcodati i vari CdL e insegnanti. Si potrebbe passare a dei file di configurazione? O sempre in dynamik o in config che poi è usato come sottomodulo git.

**Comment by VaiTon** [comment]
Se il file è un JSON cambia poco e niente, sennò dobbiamo aggiungere qualche lib per leggere a build-time, ma nulla di infattibile

**Comment by foxyseta** [comment]
Già. Propenderei per il JSON.

**Comment by foxyseta** [comment]
Come suggerito da @lucat1, questo JSON andrebbe spostato in `csunibo/config`, perché lo possa usare anche `csunibo/update`. Quindi `csunibo/config` sarà sottomodulo sia di `csunibo/dynamik` che `csunubo/update`.
