### ISSUE TITLE
Visualizzazione di file AsciiDoc

### ISSUE THREAD

**Issue by VaiTon** [csunibo/dynamik#4]
### Implementazione

~C'è questa lib su NPM, che è derivata da asciidoctor (in ruby), convertita in js via Opal: https://github.com/asciidoctor/asciidoctor.js~

~Visto che il bundle size è molto alto (> 1MB) è necessario importarlo solo se necessario, ed eventualmente fare l'operazione di rendering nella load, in modo da farla fare al server quando disponibile.~

Abbiamo deciso inizialmente di provare a compilare gli asciidoc in html e caricare quelli dal client.

### Tasks
- [x] https://github.com/csunibo/build-image/issues/1

**Comment by lucat1** [comment]
Merda e' tantissimo il bundle. A parte questo purtroppo il js verra' caricato dal client (immagino), anche se il render iniziale e' fatto dal server. Pero' si facendo il render sul server abbiamo un load iniziale piu' breve. Non esiste altro dici eh?

In alternativa per me e' okay anche far fare il lavoro a pandoc (che non potra' venire troppo male dai) da asciidoc a md

**Comment by foxyseta** [comment]
Se i tempi di esecuzione di pandoc da asciidoc a md sono tollerabili e nessun utente di asciidoc si lamenta del fatto che gli md permettano meno fronzoli per me l'idea di @lucat1 è molto buona.

**Comment by VaiTon** [comment]
Vabbè ma inizialmente va bene anche farlo fare al client. Ho provato con ssr ma non va assolutamente nulla essendo convertito da Ruby. 

C'era un iniziativa sul progetto asciidoctor.js per portarlo a wasm. Quella sarebbe una svolta assoluta.

Sinceramente convertire in md un po' ne annulla lo scopo secondo me.

E comunque: 7c906e09717fe7c04048b7c3071b6f69715b163b

**Comment by foxyseta** [comment]
Le prestazioni impattano solo chi effettivamente accede queste risorse no?

**Comment by VaiTon** [comment]
Se si fa via client si. Se compiliamo i file asciidoc a html da action in realtà non impatta nessuno e secondo me come soluzione è abbastanza ok

**Comment by lucat1** [comment]
Vediamo come viene l’output html. Asciidoctor stesso supporta html come output, quindi userei quello che è ufficiale. di base applica molti stili e cose buffe ma ho visto che si possono disabilitare

**Comment by foxyseta** [comment]
Perf siamo tutti d'accordo allora.

**Comment by samuelemusiani** [comment]
Scusate come mai questa issue è ancora aperta?

**Comment by foxyseta** [comment]
Onestamente non so se ho mai visto un contributo asciidoc in vita mia ma sì che io sappia non è mai stata implementata. Abbiamo solo aggiunto asciidoc a build-image pare.

**Comment by samuelemusiani** [comment]
Ok direi di chiudere allora perché compiliamo già lato statik

**Comment by foxyseta** [comment]
Nono io intendevo che c'è im `build-image` ma non in `statik.yml`. Forse potremmo spostare questa issue verso `csunibo/config`?

**Comment by samuelemusiani** [comment]
Ma tanto compiliamo in pdf no? Cioè statik lo prende in automatico dopo che è stato buildato

**Comment by foxyseta** [comment]
Il mio punto è che se non è in `statik.yml` non è proprio compilato. Abbiamo solo la dipendenza su `build-image`. Almeno questo è quello che ho visto io.

**Comment by samuelemusiani** [comment]
Ahh chiaro, non è un problema lo aggiungiamo
