### ISSUE TITLE
Aggiungere un collegamento alla pagina dei Build status da qualche parte

### ISSUE THREAD

**Issue by foxyseta** [csunibo/dynamik#41]
Mi pare che al momento la pagina dei Build status sia irragiungibile se non se ne si conosce l'indirizzo. Siccome è interna a Dynamik, forse io mettrei il collegamento a tale pagina da qualche parte dentro dynamik. Sennò ditemi voi.

**Comment by foxyseta** [comment]
Buona idea. Nel senso di metterlo sia su Dynamik stesso che nella wiki giusto?

**Comment by ali-benny** [comment]
> Buona idea. Nel senso di metterlo sia su Dynamik stesso che nella wiki giusto?

se per gli altri va bene per me ha senso metterlo in entrambi

**Comment by foxyseta** [comment]
Ottimo. Nel caso riesci tu ad aggiungerlo alla wiki?

**Comment by ali-benny** [comment]
Closed by  https://github.com/csunibo/wiki/pull/9
