### ISSUE TITLE
Mostrare link di telegram affianco ai corsi

### ISSUE THREAD

**Issue by lucat1** [csunibo/dynamik#47]
Vorremo mostrare il link telegram relativo all'insegnamento affianco ad ogni materia, nella pagina "dash".
Io sarei per memorizzare questi link nella stessa struttura dati che si trova in `teachings.ts`, che però andrebbe estratta in un file json da piazzare in `csunibo/config` visto che serve anche ad altri progetti come [csunibo/upld](https://github.com/csunibo/upld).

### Dipendenze
- [x] #37

**Comment by VaiTon** [comment]
Si può fare tranquillamente, visto che poi si può importare il repo nel `package.json` e importare il file json.

**Comment by VaiTon** [comment]
Related to #37

**Comment by kocierik** [comment]
sarebbero da aggiungere i gruppi telegram anche di ingegneria e cesena quando riuscite! https://github.com/csunibo/config
@VaiTon @manuandru

**Comment by manuandru** [comment]
> sarebbero da aggiungere i gruppi telegram anche di ingegneria e cesena quando riuscite! https://github.com/csunibo/config
> @VaiTon @manuandru

Attualmente, che io sappia, a Cesena usiamo una community whatsapp

**Comment by VaiTon** [comment]
> > sarebbero da aggiungere i gruppi telegram anche di ingegneria e cesena quando riuscite! https://github.com/csunibo/config
> > @VaiTon @manuandru
> 
> Attualmente, che io sappia, a Cesena usiamo una community whatsapp

Same a Bologna per Ing info, per la magistrale ci sono alcuni gruppi telegram.

**Comment by kocierik** [comment]
inseriamo sempre lo stesso link in tutti i corsi o non li mettiamo?

**Comment by foxyseta** [comment]
Vogliamo farlo? Non mi sembra un lavoro tosto

**Comment by VaiTon** [comment]
Magari apriamo una new issue però

**Comment by foxyseta** [comment]
Buona idea!
