### ISSUE TITLE
Calendario con le lezioni dei corsi

### ISSUE THREAD

**Issue by musianisamuele** [csunibo/dynamik#57]
Una pagina che mostra il calendario con le lezioni relative ai vari anni

**Comment by kocierik** [comment]
Volendo possiamo rimandare direttamente a 
https://calendar.students.cs.unibo.it/courses/8009
o all'anno accademico selezionato

**Comment by musianisamuele** [comment]
Ne stavo parlando con @VaiTon. Il fatto è che per la parte in cui calendar viene visualizzato online l'orario è "sbagliato" in quanto in UTC. Tutte le lezioni sono quindi spostate di due ore. Avendo una semplice pagine dentro il sito potremmo impostare l'orario corretto. E poi se si vuole invece aggiungere il calendario vero e proprio rimandiamo direttamente a `calendar.cs.unibo.it`

**Comment by foxyseta** [comment]
L'orario è stato sistemato ora giusto?

**Comment by VaiTon** [comment]
Questa cosa in particolare si

**Comment by foxyseta** [comment]
> Volendo possiamo rimandare direttamente a https://calendar.students.cs.unibo.it/courses/8009 o all'anno accademico selezionato

Quindi ora non ci sono più obiezioni a questo consiglio?

**Comment by VaiTon** [comment]
Per ora possiamo rimandare direttamente al sito. Magari in futuro, se vogliamo sostituire quel servizio terzo che uso per mostrare gli ICS online si può integrare su Dynamik

**Comment by musianisamuele** [comment]
L'idea era infatti di sostituire il calendario online che viene mostrato, non di sostituire completamente calendar

**Comment by foxyseta** [comment]
Ok ottimo.

**Comment by ali-benny** [comment]
@VaiTon sembra che l'orario in realtà non si sia fixato 😢

**Comment by VaiTon** [comment]
> @VaiTon sembra che l'orario in realtà non si sia fixato 😢

Puoi aprire un issue su https://github.com/VaiTon/unibocalendar/ ?

**Comment by ali-benny** [comment]
fatto csunibo/unibocalendar#8

**Comment by ali-benny** [comment]
domanda: io ho fatto lo scheletrino per il viewer del calendar... dove lo mettiamo? Qui su dynamik? nella csunibo/calendar ?

**Comment by foxyseta** [comment]
Risposto su https://github.com/orgs/csunibo/discussions/32

**Comment by VaiTon** [comment]
Chiudiamo a favore di https://github.com/orgs/csunibo/discussions/32
