### ISSUE TITLE
Pagina principale

### ISSUE THREAD

**Issue by foxyseta** [csunibo/dynamik#6]
Dobbiamo anche decidere se aggiungere qualcosa alla home prima di pubblicizzarlo e dare un sottodominio nostro all'istanza su ADM staff.

Per esempio: gli esami a scelta che non sono di nessun CdL nostro (al momento solo Metodi Logici credo) dove li infiliamo perché la gente li trovi?

**Comment by VaiTon** [comment]
> Per esempio: gli esami a scelta che non sono di nessun CdL nostro (al momento solo Metodi Logici credo) dove li infiliamo perché la gente li trovi?

Secondo me si possono mettere in ogni corso che li offre. Essendo il namespace dei corsi piatto, sono solo link alla stessa pagina.

> ...dare un sottodominio nostro all'istanza su ADM staff.

Si tratterebbe anche di tirare su un server Node se si riesce, altrimenti comunque dipenderemmo da Vercel/Netlify/Cloudflare/...

**Comment by foxyseta** [comment]
Sisi @lucat1 proponeva proprio di avere un server in ASDMStaff. Usiamo le loro infrastrutture già per altra roba. Come fallback non ricordo se vorrebbe usare GitHub pages (quindi statik) o Vercel (con dynamik)

**Comment by lucat1** [comment]
Fallback possiamo e volevamo mettere dynamik su github pages statico. dynamik può anche essere caricato statico e tutto il lavoro lo fa il client. La roba in adm va fatta anche per agevolare l’upload degli appunti che è una cosa che ci terrei a fare

**Comment by lucat1** [comment]
Per i domini, sono lunghi. Possiamo però chiedere a davoli un dominio più corto (sotto cs.unibo.it) ma non il nostro (students.cs.unibo.it). Penso che sarebbe possibile ottenerlo, ma va fatto prima di Agosto quando in italia tutti vanno in vacanza.

**Comment by foxyseta** [comment]
Per l'istanza ospitata di ADMStaff, il gruppo ha convenuto di usare `risorse.students.cs.unibo.it`.

Come consigliato da @VaiTon, gli insegnamenti a scelta che non appartengono a nessuno dei nostri CdL saranno inseriti in ogni CdL che li tollera come esami a scelta.

Grazie!
