### ISSUE TITLE
Corsi a scelta

### ISSUE THREAD

**Issue by kocierik** [csunibo/dynamik#60]
Per quanto riguarda i corsi a scelta come vogliamo gestire la visualizzazione?
io gli aggiungerei specificando una sezione dove sia chiaro che i corsi siano a scelta, un pò come nella vecchia versione.

Mentre per il file courses.json, presente nella repo di config, avete idee particolari sul come aggiungere i corsi a scelta nel json?

**Comment by foxyseta** [comment]
OT: siccome ora aggiungiamo i nuovi insegnamenti a `courses.json` anziché hardcodarli in `teaching.ts` va aggiornata https://csunibo.github.io/wiki/raccolte-di-risorse/aggiungere-un-nuovo-insegnamento/index.html giusto?

@csunibo/frontend possiamo parlarne assieme.

I corsi a scelta del nostro dipartimento mi pare si dividano in due categorie:
1. corsi a scelta da lista (c'è l'obbligo di prenderli da una lista limitata);
2. corsi a libera scelta (o li si prende dalla lista o si becca il giusto SSD).

In entrambi i casi, l'anno è sempre specificato nel piano didattico, quindi come rappresentazione interna potremmo dividere ciascun anno di piano didattico in "obbligatori" a "scelta" (nomi provvisori). Il campo "scelta" è, di per sé, opzionale.

Nella UI web anche a me piace l'idea di emulare il vecchio statik, mettendo un titolo "Scelta" dentro il giusto anno (siccome in magistrale ci sono esami a scelta in entrambi gli anni), ma sottointendendo il titolo "obbligatori".

**Comment by kocierik** [comment]
si, per quando riguarda la documentazione va aggiornata! 

Mentre per la definizione del json vogliamo adottare questa struttura o avete alternative? 
```
    "years": [
      {
        "year": 1,
        "teachings": [...]
        "optionals": [...]
      }
]
 ```

**Comment by VaiTon** [comment]
> Nella UI web anche a me piace l'idea di emulare il vecchio statik, mettendo un titolo "Scelta" dentro il giusto anno (siccome in magistrale ci sono esami a scelta in entrambi gli anni), ma sottointendendo il titolo "obbligatori".

Magari utilizzerei qualche icona al posto di "scelta", per poi mettere nel hover "Corso a scelta". Alla fine i corsi sono solamente ordinati in base all'ordine che c'è nel file.

Riguardo alla struttura del file, terrei solo un teachings ma direi di fare come proponeva @foxyseta, ovvero di aggiungere una proprietà opzionale

```
...
teachings: [
  {
    ...
    optional: true
]
```

**Comment by kocierik** [comment]
andata per optional

**Comment by foxyseta** [comment]
> si, per quando riguarda la documentazione va aggiornata!

Aggiornata la documentazione in https://github.com/csunibo/wiki/commit/d50d4423251d3247a0d191ced79d377e448cb25d
