### ISSUE TITLE
Anterpima dei link e favicon

### ISSUE THREAD

**Issue by foxyseta** [csunibo/dynamik#7]
Il nostro modello per statik al momento come anteprima dei link e favicon mette il logo di CSUnibo. Come titolo e descrizione dell'anteprima si può pensare a qualcosa (al momento usiamo percorso della cartella e poco altro).

**Comment by ali-benny** [comment]
Cosa vogliamo inserire nell'anteprima quindi?

Sto provando a fare delle immagini da aggiungere come questa...
![risorse students cs unibo it](https://github.com/csunibo/dynamik/assets/74602443/70bd0542-5530-4ed1-8e87-8061a5cd17a7)

Sul gruppo telegram si era parlato di eventuale nuovo logo dedicato al "Dynamic" ma con un altro nome [che casino]. 
Posso provare a crearne uno senza nomi/scritte

**Comment by foxyseta** [comment]
A me quello che hai fatto qui piace molto. Immagino le scritte si leggano dalle anteprime telegram?

**Comment by ali-benny** [comment]
> A me quello che hai fatto qui piace molto. Immagino le scritte si leggano dalle anteprime telegram?

non ho provato, ma spero di si, nel caso modifico senza problemi :D
