### ISSUE TITLE
BUG: 404 page not found

### ISSUE THREAD

**Issue by musianisamuele** [csunibo/dynamik#74]
A seguito del commit 424d673ca5ac7c9f7785212f28c8ecad4caf2805, tutte le pagine dei corsi restituiscono l'errore 404. L'istanza su https://risorse.students.cs.unibo.it funziona perché ho fatto un reset ad un commit precedente. L'instanza su https://dynamik.vercel.app mostra l'errore in questione

**Comment by VaiTon** [comment]
Come ti scrivevo in pvt:

> Giustamente si doveva aggiornare l'env. Non pensavo venisse deployato se rotto da vercel
> Basta definire un VITE_UPLD_URL come env. Per ora lo puoi fare puntare anche a 0.0.0.0.

**Comment by VaiTon** [comment]
Ora aggiorno su vercel

**Comment by musianisamuele** [comment]
Perfetto, risolto
