### ISSUE TITLE
Generalizzazione link alle community

### ISSUE THREAD

**Issue by foxyseta** [csunibo/dynamik#96]
Come discusso in #47, molti CdL usano Whatsapp per i corsi degli insegnamenti. Si potrebbe generalizzare il pulsante delle chat affinché supporti anche Whatsapp. Per farlo, i link alle chat Whatsapp devono prima essere memorizzati in `courses.json`. Prerequisito di questa issue è quindi:
- [x] https://github.com/csunibo/config/issues/10

~Da capire come gestire il caso (caotico ma possibile) in cui `courses.json` contenga sia un gruppo Whatsapp che uno Telegram.~

**Comment by VaiTon** [comment]
Adesso si deve aggiornare il tipo e l'usage
